logging:
   config: file:/usr/local/etc/gateway/logback.xml
gateway:
   security:
      excludes: /ExempleService, /ExempleService/, /*/info, /*/*/info, /*/health, /*/*/health, /*/ws/v1/schemas/**, /*/*/*/openapi.json, /ExempleAuthorization/oauth/*, /*/.well-known/jwks.json
      csrf:
         excludes: /ExempleAuthorization/oauth/*, /ExempleAuthorization/login
spring:
   hazelcast:
      config: file:/usr/local/etc/gateway/hazelcast.yaml
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: http://172.17.0.1:8090/ExempleAuthorization/oauth/jwks
   cloud:
      gateway:
         httpclient:
            connect-timeout: 1000
            response-timeout: 60s
         server:
            webflux:
               routes:
               -  id: api-service
                  uri: http://172.17.0.1:8080/ExempleService
                  predicates:
                  - Path=/ExempleService/**
                  filters:
                  - RewriteLocationResponseHeader=NEVER_STRIP, Location, ,
                  - AccessTokenRelay=
                  - RemoveRequestHeader=cookie
                  - RemoveRequestHeader=x-xsrf-token
               -  id: authorization-token
                  uri: http://172.17.0.1:8090/ExempleAuthorization
                  predicates:
                  - Path=/ExempleAuthorization/oauth/token
                  filters:
                  - RewriteLocationResponseHeader=NEVER_STRIP, Location, ,
                  - OAuthAccessToken=
                  - AddCsrfToken=
               -  id: authorization-authorize
                  uri: http://172.17.0.1:8090/ExempleAuthorization
                  predicates:
                  - Path=/ExempleAuthorization/oauth/authorize
                  filters:
                  - AccessTokenRelay=
                  - RemoveRequestHeader=cookie
                  - RemoveRequestHeader=x-xsrf-token
                  - SetStatus200IfRedirection=
               -  id: authorization-login
                  uri: http://172.17.0.1:8090/ExempleAuthorization
                  predicates:
                  - Path=/ExempleAuthorization/login
                  filters:
                  - AccessTokenRelay=
                  - RemoveRequestHeader=cookie
                  - RemoveRequestHeader=x-xsrf-token
                  - RemoveResponseHeader=Location
                  - SetStatus200IfRedirection=
               -  id: authorization-service
                  uri: http://172.17.0.1:8090/ExempleAuthorization
                  predicates:
                  - Path=/ExempleAuthorization/**
                  filters:
                  - RewriteLocationResponseHeader=NEVER_STRIP, Location, ,
                  - AccessTokenRelay=
                  - RemoveRequestHeader=cookie
                  - RemoveRequestHeader=x-xsrf-token